### ISSUE TITLE
Incorrect version number

### ISSUE THREAD

**Issue by asjmcguire** [broglep/homeassistant-meshtastic#13]
## System Information

version | core-2024.12.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.13.0
os_name | Linux
os_version | 6.6.66-haos
arch | x86_64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4994
Installed Version | 2.0.1
Stage | running
Available Repositories | 1501
Downloaded Repositories | 40

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 20 November 2025 at 00:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
cloud_ice_servers_enabled | true
remote_server | eu-central-1-11.ui.nabu.casa
certificate_status | ready
instance_id | d74dbc9c9b6b4563b25a3c274331fe7a
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 14.1
-- | --
update_channel | stable
supervisor_version | supervisor-2024.12.0
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 30.8 GB
disk_used | 14.3 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | kvm
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Matter Server (6.6.1), Home Assistant Google Drive Backup (0.112.1), File editor (5.8.0), Samba share (12.3.2), ESPHome Device Builder (2024.12.2), Terminal & SSH (9.16.0), Whisper (2.4.0), Piper (1.5.2), Auto Guest Login (1.4.0), Node-RED (18.1.1), Music Assistant Server (beta) (2.4.0b7), Govee to MQTT Bridge (2024.07.13-82ddc6e9), OpenThread Border Router (2.12.2), chrony (5.0.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 11
-- | --
resources | 18
views | 64
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 5 December 2024 at 10:55
-- | --
current_recorder_run | 22 December 2024 at 11:51
estimated_db_size | 3536.62 MiB
database_engine | mysql
database_version | 10.7.8

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/broglep/homeassistant-meshtastic/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

The HACS download screen shows v0.2.0 and Github claims to be Alpha v0.2.0 too.
But in https://github.com/broglep/homeassistant-meshtastic/blob/main/custom_components/meshtastic/manifest.json it still states v0.1.0 and inside Home Assistant it stated 0.1.0

### Reproduction steps

1. Download from HACS
2. Restart Home Assistant
3. Add integration into Home Assistant
4. Observe reported version.
...

### Debug logs

```text
No debug needed
```

**Comment by broglep** [comment]
Thanks, missed that one, will adjust for the next release that should soon be available
